import { getAnthropic, ANTHROPIC_MODEL } from "@/lib/ai/anthropic";
import { classifyProduct, type Classification } from "@/lib/data/classifier";
import { lookupTariff } from "@/lib/data/tariffs";

// Prefer Claude when ANTHROPIC_API_KEY is set; fall back to the keyword
// classifier otherwise. Same return shape either way so callers don't care.

const SYSTEM_PROMPT = `You are an expert customs broker specialising in the WCO HS 2022 nomenclature and the African Continental Free Trade Area (AfCFTA) tariff schedules.

Given a free-text product description, return a single HS-4 code (4-digit chapter+heading) that best classifies it, with a confidence score and a short rationale.

Rules:
- Use only valid HS 2022 codes.
- Confidence is a float between 0.0 and 1.0; reserve >0.9 for unambiguous descriptions.
- If multiple codes are plausible, return the most likely and list up to 3 alternates.
- Reasoning must cite the chapter/heading text that drove the decision.

Respond ONLY with JSON matching this schema, no prose:
{
  "hsPrefix": "0901",
  "description": "Coffee, not roasted, not decaffeinated",
  "confidence": 0.95,
  "reasoning": "string",
  "alternates": [{ "hsPrefix": "0902", "description": "...", "confidence": 0.1 }]
}`;

export async function classifyWithAI(description: string): Promise<Classification & { source: "ai" | "keyword"; reasoning?: string }> {
  const anthropic = getAnthropic();

  // No key? Use the deterministic keyword classifier.
  if (!anthropic) {
    const result = classifyProduct(description);
    return { ...result, source: "keyword" };
  }

  try {
    const msg = await anthropic.messages.create({
      model: ANTHROPIC_MODEL,
      max_tokens: 600,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: description }]
    });

    const text = msg.content
      .filter((b) => b.type === "text")
      .map((b) => ("text" in b ? b.text : ""))
      .join("");

    // Strip code fences if Claude wrapped JSON in them.
    const cleaned = text.replace(/^```(?:json)?\s*|```\s*$/g, "").trim();
    const parsed = JSON.parse(cleaned) as {
      hsPrefix: string;
      description: string;
      confidence: number;
      reasoning?: string;
      alternates?: Array<{ hsPrefix: string; description: string; confidence: number }>;
    };

    return {
      hsPrefix: parsed.hsPrefix,
      description: parsed.description,
      confidence: parsed.confidence,
      tariff: lookupTariff(parsed.hsPrefix),
      alternates: (parsed.alternates ?? []).slice(0, 3).map((a) => ({
        hsPrefix: a.hsPrefix,
        description: a.description,
        confidence: a.confidence
      })),
      reasoning: parsed.reasoning,
      source: "ai"
    };
  } catch (err) {
    console.warn("[ai/classify] AI call failed, falling back to keyword:", err);
    const result = classifyProduct(description);
    return { ...result, source: "keyword" };
  }
}

// Helper for plain-language Rules of Origin explanation generated by Claude
const ROO_SYSTEM_PROMPT = `You are an AfCFTA Rules of Origin specialist. Given a determination result, write a plain-language explanation (2-4 sentences) tailored to a small African exporter who is not a customs expert.

Be concrete about what they did right or what they need to change. Cite the rule that applies.`;

export async function explainOriginWithAI(input: {
  hsChapter: string;
  rule: string;
  qualifies: "yes" | "no" | "marginal";
  factsConfirmedByUser: string[];
}): Promise<string | null> {
  const anthropic = getAnthropic();
  if (!anthropic) return null;

  try {
    const msg = await anthropic.messages.create({
      model: ANTHROPIC_MODEL,
      max_tokens: 250,
      system: ROO_SYSTEM_PROMPT,
      messages: [{ role: "user", content: JSON.stringify(input) }]
    });
    const text = msg.content
      .filter((b) => b.type === "text")
      .map((b) => ("text" in b ? b.text : ""))
      .join("");
    return text.trim();
  } catch (err) {
    console.warn("[ai/explainOrigin] failed:", err);
    return null;
  }
}
